# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Character.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Character(object):
    def setupUi(self, Character):
        Character.setObjectName("Character")
        Character.resize(480, 452)
        self.verticalLayout = QtWidgets.QVBoxLayout(Character)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(Character)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.tabWidget = QtWidgets.QTabWidget(Character)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.intelligenceValueLabel = QtWidgets.QLabel(self.mainTab)
        self.intelligenceValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.intelligenceValueLabel.setObjectName("intelligenceValueLabel")
        self.gridLayout.addWidget(self.intelligenceValueLabel, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.mainTab)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.mainTab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.strengthValueLabel = QtWidgets.QLabel(self.mainTab)
        self.strengthValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.strengthValueLabel.setObjectName("strengthValueLabel")
        self.gridLayout.addWidget(self.strengthValueLabel, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.mainTab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.charismaValueLabel = QtWidgets.QLabel(self.mainTab)
        self.charismaValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.charismaValueLabel.setObjectName("charismaValueLabel")
        self.gridLayout.addWidget(self.charismaValueLabel, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.mainTab)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.dexterityValueLabel = QtWidgets.QLabel(self.mainTab)
        self.dexterityValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dexterityValueLabel.setObjectName("dexterityValueLabel")
        self.gridLayout.addWidget(self.dexterityValueLabel, 1, 1, 1, 1)
        self.constitutionValueLabel = QtWidgets.QLabel(self.mainTab)
        self.constitutionValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constitutionValueLabel.setObjectName("constitutionValueLabel")
        self.gridLayout.addWidget(self.constitutionValueLabel, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.mainTab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.wisdomValueLabel = QtWidgets.QLabel(self.mainTab)
        self.wisdomValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wisdomValueLabel.setObjectName("wisdomValueLabel")
        self.gridLayout.addWidget(self.wisdomValueLabel, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.mainTab)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.luckValueLabel = QtWidgets.QLabel(self.mainTab)
        self.luckValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.luckValueLabel.setObjectName("luckValueLabel")
        self.gridLayout.addWidget(self.luckValueLabel, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.mainTab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 6, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.raceLabel = QtWidgets.QLabel(self.mainTab)
        self.raceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.raceLabel.setObjectName("raceLabel")
        self.horizontalLayout_4.addWidget(self.raceLabel)
        self.raceComboBox = QtWidgets.QComboBox(self.mainTab)
        self.raceComboBox.setEnabled(True)
        self.raceComboBox.setEditable(False)
        self.raceComboBox.setObjectName("raceComboBox")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.raceComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.raceComboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.raceLabel_2 = QtWidgets.QLabel(self.mainTab)
        self.raceLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.raceLabel_2.setObjectName("raceLabel_2")
        self.horizontalLayout.addWidget(self.raceLabel_2)
        self.sizeValueLabel = QtWidgets.QLabel(self.mainTab)
        self.sizeValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sizeValueLabel.setObjectName("sizeValueLabel")
        self.horizontalLayout.addWidget(self.sizeValueLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acLabel = QtWidgets.QLabel(self.mainTab)
        self.acLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.acLabel.setObjectName("acLabel")
        self.horizontalLayout_3.addWidget(self.acLabel)
        self.acValueLabel = QtWidgets.QLabel(self.mainTab)
        self.acValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.acValueLabel.setObjectName("acValueLabel")
        self.horizontalLayout_3.addWidget(self.acValueLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hpLabel = QtWidgets.QLabel(self.mainTab)
        self.hpLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hpLabel.setObjectName("hpLabel")
        self.horizontalLayout_2.addWidget(self.hpLabel)
        self.hpValueLabel = QtWidgets.QLabel(self.mainTab)
        self.hpValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hpValueLabel.setObjectName("hpValueLabel")
        self.horizontalLayout_2.addWidget(self.hpValueLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.mainTab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.mainTab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 1, 1, 1)
        self.tabWidget.addTab(self.mainTab, "")
        self.equipmentTab = QtWidgets.QWidget()
        self.equipmentTab.setObjectName("equipmentTab")
        self.tabWidget.addTab(self.equipmentTab, "")
        self.skillsMagicTab = QtWidgets.QWidget()
        self.skillsMagicTab.setObjectName("skillsMagicTab")
        self.tabWidget.addTab(self.skillsMagicTab, "")
        self.personalityTab = QtWidgets.QWidget()
        self.personalityTab.setObjectName("personalityTab")
        self.tabWidget.addTab(self.personalityTab, "")
        self.historyTab = QtWidgets.QWidget()
        self.historyTab.setObjectName("historyTab")
        self.tabWidget.addTab(self.historyTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.idLabel = QtWidgets.QLabel(Character)
        self.idLabel.setTextFormat(QtCore.Qt.PlainText)
        self.idLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.idLabel.setObjectName("idLabel")
        self.verticalLayout.addWidget(self.idLabel)

        self.retranslateUi(Character)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Character)

    def retranslateUi(self, Character):
        _translate = QtCore.QCoreApplication.translate
        Character.setWindowTitle(_translate("Character", "Form"))
        self.nameLineEdit.setPlaceholderText(_translate("Character", "Character Name"))
        self.intelligenceValueLabel.setText(_translate("Character", "+0"))
        self.label_11.setText(_translate("Character", "Wisdom"))
        self.label_5.setText(_translate("Character", "Dexterity"))
        self.strengthValueLabel.setText(_translate("Character", "+0"))
        self.label_7.setText(_translate("Character", "Constitution"))
        self.charismaValueLabel.setText(_translate("Character", "+0"))
        self.label_15.setText(_translate("Character", "Luck"))
        self.dexterityValueLabel.setText(_translate("Character", "+0"))
        self.constitutionValueLabel.setText(_translate("Character", "+0"))
        self.label_9.setText(_translate("Character", "Intelligence"))
        self.wisdomValueLabel.setText(_translate("Character", "+0"))
        self.label_13.setText(_translate("Character", "Charisma"))
        self.luckValueLabel.setText(_translate("Character", "+0"))
        self.label_3.setText(_translate("Character", "Strength"))
        self.raceLabel.setText(_translate("Character", "Race"))
        self.raceComboBox.setCurrentText(_translate("Character", "Human"))
        self.raceComboBox.setItemText(0, _translate("Character", "Human"))
        self.raceComboBox.setItemText(1, _translate("Character", "Wood Elf"))
        self.raceComboBox.setItemText(2, _translate("Character", "High Elf"))
        self.raceComboBox.setItemText(3, _translate("Character", "Hill Dwarf"))
        self.raceComboBox.setItemText(4, _translate("Character", "Mountain Dwarf"))
        self.raceComboBox.setItemText(5, _translate("Character", "Dark Elf"))
        self.raceComboBox.setItemText(6, _translate("Character", "Gnome"))
        self.raceComboBox.setItemText(7, _translate("Character", "Halfling"))
        self.raceComboBox.setItemText(8, _translate("Character", "Half-elf"))
        self.raceComboBox.setItemText(9, _translate("Character", "Half-orc"))
        self.raceComboBox.setItemText(10, _translate("Character", "Dragonborn"))
        self.raceComboBox.setItemText(11, _translate("Character", "Tiefling"))
        self.raceLabel_2.setText(_translate("Character", "Size"))
        self.sizeValueLabel.setText(_translate("Character", "medium"))
        self.acLabel.setText(_translate("Character", "AC"))
        self.acValueLabel.setText(_translate("Character", "10"))
        self.hpLabel.setText(_translate("Character", "HP"))
        self.hpValueLabel.setText(_translate("Character", "100"))
        self.label.setText(_translate("Character", "Speed"))
        self.label_2.setText(_translate("Character", "30\'"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("Character", "Vital Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.equipmentTab), _translate("Character", "Equipment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.skillsMagicTab), _translate("Character", "Skills / Magic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.personalityTab), _translate("Character", "Personality"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historyTab), _translate("Character", "History"))
        self.idLabel.setText(_translate("Character", "00000"))

