weapon_types = [
        "club",
        "dagger",
        "hand axe",
        "javelin",
        "light hammer",
        "mace",
        "quarterstaff",
        "sickle",
        "spear",
        "unarmed",
        "light crossbow",
        "dart",
        "short bow",
        "sling",
        "battleaxe",
        "flail",
        "glaive",
        "greataxe",
        "greatsword",
        "halberd",
        "lance",
        "longsword",
        "maul",
        "morningstar",
        "pike",
        "rapier",
        "scimitar",
        "shortsword",
        "trident",
        "war pick",
        "warhammer",
        "whip",
        "blowgun",
        "hand crossbow",
        "heavy crossbow",
        "longbow",
        "net",
        ]
